README.md
index.qmd

This PR removes the proof of concept note from the Quarto Extensions Listing. The note is no longer necessary as the repository is now fully functional.

docs: remove proof of concept note

---

extensions/quarto-extensions.csv

I deleted `formats,coatless-quarto/hsnr-revealjs` as that's covered by `formats,produnis/hsnr-revealjs`

chore: Add a few extensions

---

_quarto.yml

Update the styling of categories to display them in upper case. This change adds a CSS rule to transform the text of category labels to uppercase.

style: Categories as Upper Case

---

.github/workflows/quarto-web.yml
extensions/quarto-extensions.csv

This pull request adds a new GitHub Actions workflow that automatically retrieves extensions submitted to Quarto.org. The workflow runs on a weekly schedule and fetches the extensions from the Quarto website. The retrieved extensions are then added to the `quarto-extensions.csv` file. This ensures that the list of Quarto extensions is always up to date.
Fixes #49

ci: Automatically retrieve extensions submitted to Quarto.org

---

.github/workflows/check-extensions.yml

This pull request removes the category field from the topics/description CSV structure. The category field was causing issues when checking extensions, so it has been removed to simplify the structure and improve the extension checking process.

ci: Remove category from topics/description CSV structure

---

extensions/make-yaml.sh

The `make-yaml.sh` script has been updated to escape HTML tags with backticks using sed. This ensures that HTML tags are properly escaped in the repository description.
Fixes #60

fix: handle unescaped HTML tags

---

extensions/quarto-extensions.csv

This pull request removes the duplicated extension "coatless/quarto-illinois" from the `quarto-extensions.csv` file.

chore: Remove duplicated extension

---

extensions/quarto-extensions.csv

Adds a new `{{< base64 >}}` and `{{< base64-data >}}` shortcode from [gadenbuie/quarto-base64](https://pkg.garrickadenbuie.com/quarto-base64/) to the list of extensions.

Add gadenbuie/quarto-base64

---

.github/workflows/check-extensions.yml

This pull request fixes the issue #84 where the duplicate check was case sensitive. The check should be case insensitive. The changes include modifying the code to use case-insensitive comparison when checking for duplicates in the `extensions/quarto-extensions.csv` file.

ci: fix case sensitivity in duplicate check

---

assets/ejs/authors.ejs

This pull request fixes the issue where the zero star author count was not being displayed. The problem was caused by a conditional statement that was incorrectly checking for the presence of the `stars` property. This pull request removes the unnecessary conditional statements and ensures that the zero star author count is correctly displayed.
Fixes #87

fix: display of zero star author count

---

.github/workflows/quarto-web.yml

This pull request fixes #90 where the GitHub Actions (GHA) workflow was retrieving extensions from quarto.org in a case-sensitive manner. The patch modifies the `quarto-web.yml` file to use a case-insensitive grep command (`grep -Fvxi`) when comparing the extensions in the `quarto-extensions.csv` and `quarto-web-extensions.csv` files.

ci: case sensitivity issue in extensions retrieval

---

assets/stylesheets/theme.scss

The button is now initially hidden and becomes visible with a fade-in effect when the mouse hovers over the code block.

feat: copy button only on hover

---

authors.qmd
index.qmd

This pull request ensures that the title metadata and page titles are correctly displayed without the counts in browsers.

fix: hide counts in title metadata

---

.github/workflows/quarto-web.yml

Update the CI workflow to remove the 'blob' component from repository paths when generating the CSV file for extensions.

ci: remove blob component from repository paths in CI workflow

---

extensions/quarto-extensions.csv

Introduce new quarto extensions, including typst templates and additional pandoc extensions.

chore: add quarto-ext/typst extensions and few others

---

extensions/quarto-extensions.csv

Remove the recently added typst templates from the quarto extensions list as they all share the same metadata thus they can't all be actually listed.

revert: addition of quarto-ext/typst-templates

---

assets/ejs/extensions.ejs

The changes ensure that categories in the card correctly encode the category names, resolving the issue where categories did not function as intended. Fixes #136

fix: categories in card functionality

---

assets/ejs/extension-install-modal.ejs
assets/ejs/extensions.ejs
assets/scripts/make-yaml.sh
assets/stylesheets/extensions.scss

Implement the Quarto Wizard installation options in the extension installation modal. This change enhances the user experience by providing a streamlined method for installing extensions via the Quarto Wizard.
Fixes #138

feat: use Quarto Wizard for installation options

---

.github/workflows/quarto-wizard.yml

Fetch the content of `template.qmd` as a base64 encoded string. This change ensures that the template content is readily available for further processing.

feat: fetch template.qmd as base64

---

assets/ejs/extension-install-modal.ejs
assets/ejs/extension-use-modal.ejs
assets/ejs/extensions.ejs

Modals previously displayed only the first value on the page. Update ensures each modal correctly references its respective value, allowing for accurate display and interaction.
Fixes #156

fix: modal display issue for multiple values

---

.github/workflows/test-extensions.yml

Introduce a GitHub Actions workflow to automate the testing of Quarto extensions, ensuring that extensions with examples or templates are validated during pushes to the `quarto-wizard` branch.

feat: add GitHub Actions workflow for testing Quarto extensions.

---

README.md
extensions/quarto-extensions.csv

I suggest adding a line to the `quarto-extensions` readme to inform contributors that they should have a release/tag on their extensions.

chore: add release requirement to readme

---

_extensions/mcanouil/iconify/_extension.yml
_extensions/mcanouil/iconify/iconify.lua

Upgrade the Iconify extension to the latest version, which includes enhancements and deprecation warnings for configuration changes.

chore: update Iconify extension to version 3.0.1

---

index.qmd

Eliminate the page title from the extensions listing.

fix: remove page title from extensions listing page
