mcanouil/quarto-extensions

.gitignore, extensions/quarto-extensions.csv
This pull request adds new extensions to the project. The extensions include `quarto-lapreprint`, `minimal-doc`, `quarto-now`, and `hsnr-revealjs`. These extensions enhance the functionality and capabilities of the project.
=> feat: Add extensions

extensions/quarto-extensions.csv
https://pkg.garrickadenbuie.com/revealjs-text-resizer/
=> Add gadenbuie/revealjs-text-resizer

extensions/quarto-extensions.csv
=> feat: add AndreasThinks/quarto-mastodon-comments & ihrke/mdpi

extensions/quarto-extensions.csv
CC. @leovan, @dragonstyle, @dialoa, @coatless, @christopherkenny, @dfolio, @AaronGullickson
=> feat: add multiple extensions

extensions/make-yaml.sh
=> fix: Trim `quarto-` rather than excluding completely topics

extensions/make-yaml.sh
This pull request refactors the code to reduce the number of API calls made. The changes include optimising the retrieval of repository owner information and author details. This optimisation helps improve the performance and efficiency of the code.
=> refactor: reduce api calls

extensions/make-yaml.sh
This pull request refactors the use of the repo view payload to include additional information such as the latest release, license info, stargazer count, and repository topics. This allows for a more comprehensive representation of the repository in the generated YAML file.
=> refactor: use repo view payload for topics

_quarto.yml, extensions.qmd, extensions/make-yaml.sh
This pull request includes improvements to the JS script and adds new features such as displaying stars, license information, and display as a grid listing.
=> feat: Improve JS script and add stars, license, and switch to grid listing

extensions.qmd, extensions/make-yaml.sh
This pull request fixes the description length and sorting in the `extensions.qmd` file. The sorting options for the grid UI have been updated to include sorting by title, date, author, and file modified. Additionally, the maximum description length has been set to 500 characters.
=> fix: description length and improve sorting

_quarto.yml, assets/stylesheets/theme.scss, extensions.qmd, index.qmd
This pull request updates the styling of the Quarto Extensions website. It includes changes to the `_quarto.yml`, `assets/stylesheets/theme.scss`, `extensions.qmd`, and `index.qmd` files. The changes include tweaks to the metadata and layout, as well as the addition of a new theme stylesheet. These updates improve the overall appearance and user experience of the website.
=> style: tweak metadata and layout

extensions/quarto-extensions.csv
=> chore: add pagiraud/fullframegraphics

.github/workflows/quarto-web.yml
The commit command in the quarto-web.yml file was not working correctly. This pull request fixes the issue by updating the commit command to include the correct file.
=> ci(quarto-web.yml): fix commit command

README.md, index.qmd
This pull request adds a pattern/example for submission to the Quarto extensions repository. The pattern/example provides clear instructions on how to add an extension to the repository by making a pull request. It also includes an example of the required format for adding an extension. This addition will make it easier for contributors to submit their extensions and improve the overall user experience.
=> docs: add pattern/example for submission

.gitignore, README.md, _quarto.yml, index.qmd
This pull request includes a style tweak to the index page layout.
=> style: tweak index page layout

extensions/make-yaml.sh
The default command should now use the version when there is one.
Fixes #42.
=> feat: default command now uses version

.gitignore, assets/stylesheets/theme.scss, extensions/_author-listing.qmd, extensions/make-yaml.sh
This pull request adds an "author" listing feature to the project. It includes the following changes:
- Added a new file `extensions/_author-listing.qmd` that defines the structure and content of the author listing.
- Modified the `extensions/make-yaml.sh` script to generate YAML files for each author and populate the author listing with their information.
- Updated the `.gitignore` file to include the new `extensions/authors` directory.
- Removed some CSS code from `assets/stylesheets/theme.scss` that was no longer needed.
Fixes #43
=> feat: Add "author" listing

authors.qmd
=> fix: use proper field for filtering

extensions/quarto-extensions.csv
Another new shortcode extension to inline partial content with mustache-templating.
https://pkg.garrickadenbuie.com/quarto-partials/
=> chore: Add gadenbuie/quarto-partials

.github/workflows/quarto-web.yml
This pull request adds a check to see if there are any new extensions before committing and pushing changes. If there are no new extensions, the commit and push steps are skipped.
=> ci: Check if there are new extensions before committing and pushing

_quarto.yml, assets/ejs/authors.ejs, assets/stylesheets/authors.scss
This pull request improves the visual appeal and interactivity of the author cards.
=> style: Add hover effect to author cards

extensions/quarto-extensions.csv
Manuscript style inspired by Edward Tufte's books layout.
=> chore: add fredguth/tufte-inspired extension

_quarto.yml, assets/ejs/extensions.ejs, assets/quarto/_author-listing.qmd, assets/stylesheets/extensions.scss, index.qmd
This pull request adds custom EJS for extensions. It includes a new EJS file for extensions, updates the configuration file to include the new EJS file, and adds a new SCSS file for styling the extensions.
=> feat: customise the EJS listing for extensions

_quarto.yml, about.qmd, assets/ejs/authors.ejs, assets/ejs/extensions.ejs, assets/quarto/_author-listing.qmd, assets/scripts/current-year.html, assets/scripts/make-yaml.sh, assets/stylesheets/theme.scss, index.qmd
=> refactor: remove markdown in YAML content and improve search/filter

.github/workflows/check-extensions.yml
This pull request replaces single quotes with double quotes in the shell commands to allow the use of bash variables.
=> ci: replace single quotes to allow bash variables

extensions/quarto-extensions.csv
=> Add i18n extension

extensions/quarto-extensions.csv
https://pkg.garrickadenbuie.com/quarto-bluesky-comments/
=> Add gadenbuie/quarto-bluesky-comments

_quarto.yml, assets/scripts/categories-alphabetical.html
Implement a script that organises categories in listings alphabetically (collapsed), enhancing user navigation and accessibility.
=> feat: add alphabetical categorisation for listings

.github/workflows/quarto-wizard.yml
Implement a CI workflow to fetch and update extension details from the Quarto website, generating a JSON file from the CSV list of extensions. This workflow triggers on specific events such as releases and scheduled times.
=> ci: add GitHub Actions workflow for Quarto Wizard extensions updates

_quarto.yml, about.qmd, assets/ejs/authors.ejs, assets/ejs/extension-install-modal.ejs, assets/ejs/extensions.ejs, assets/quarto/_author-listing.qmd, assets/stylesheets/extensions.scss, assets/stylesheets/theme.scss
Introduce titles and labels for icons to enhance accessibility and clarity. Remove anchors from modal headers to improve user experience.
=> feat: Add titles and labels for icons, and remove anchors in modals

.github/workflows/deploy.yml, .github/workflows/quarto-wizard.yml, .gitignore, assets/ejs/extensions.ejs, assets/scripts/make-yaml.sh, assets/stylesheets/extensions.scss
Consolidate the management of Quarto extensions by transitioning to a JSON-based approach, enhancing maintainability and consistency across workflows. This change simplifies the data handling process and improves the overall structure of the project in coordination with the Quarto Wizard VSCode extension.
=> refctor: use a single source of truth as JSON

.gitignore, assets/ejs/extensions.ejs, assets/quarto/_author-listing.qmd, assets/scripts/make-yaml.sh, assets/stylesheets/extensions.scss
Introduce functionality to copy and add social cards for repositories. This enhancement includes updates to the author listing and image handling, ensuring that repository images are fetched and displayed correctly. Adjustments to the styles improve the visual presentation of the cards.
=> feat: add repository social card functionality

assets/ejs/extension-use-modal.ejs, assets/ejs/extensions.ejs, assets/scripts/make-yaml.sh
Introduce a modal for using templates, enhancing user interaction by providing options for manual usage and integration with the Quarto Wizard extension. Update the script to include template information in the YAML output.
=> feat: add template usage modal functionality

.github/workflows/check-extensions.yml, extensions/quarto-extensions.csv
Refactor the workflow to use base git commands for checking extensions.
=> ci: refactor extension checks

.github/workflows/quarto-wizard.yml
Enhance the workflow to retrieve example content from the specified repository. Update repository information to reflect the presence of example content and its status.
=> feat: add support for fetching repository example content

assets/ejs/extension-use-modal.ejs
Add functionality to enable the use template modal, enhancing user interaction with the template selection process.
=> feat: enable use template modal

extensions/quarto-extensions.csv
Add [`code-appendix`](https://github.com/cl-roberts/code-appendix) to quarto extensions spreadsheet.
This extension auto-generates an appendix from code chunks on rendering `.qmd` files.
=> chore: add code-appendix

_quarto.yml, assets/brand/dark.yml, assets/brand/light.yml, assets/ejs/extension-install-modal.ejs, assets/ejs/extension-use-modal.ejs, assets/scripts/make-yaml.sh, assets/stylesheets/authors.scss, assets/stylesheets/extensions.scss, assets/stylesheets/theme.scss
Introduce separate light and dark mode styles.
=> style: light and dark mode themes

extensions/quarto-extensions.csv
I confirm that I have checked that:
- There are no special characters/strings in the **Description**, such as `'<style>'` instead of `` `<style>` ``.
=> chore: Update quarto-extensions.csv

extensions/quarto-extensions.csv
I confirm that I have checked that:
- There are no special characters/strings in the **Description**, such as `'<style>'` instead of `` `<style>` ``.
Converts .png images in your Quarto document to lossless .webp format when rendering to HTML. This improves compression while retaining quality. Particularly useful for images generated by R or Python code chunks, such as diagrams.
=> add klausbrunner/convert-to-webp

extensions/quarto-extensions.csv
add jjdeclercq/alert_shortcode
I confirm that I have checked that:
- There are no special characters/strings in the **Description**, such as `'<style>'` instead of `` `<style>` ``.
A framework for creating Quarto callouts using YAML. Additional inputs allow for tracking and logging issues throughout the lifespan of the document.
=> chore: update quarto-extensions.csv add jjdeclercq/alert_shortcode

.github/workflows/quarto-wizard.yml
Refactor the workflow to maintain individual extension details and implement a summary of updated and skipped extensions. This enhances clarity and tracking of changes during the extension update process, while reducing number of API calls.
=> ci: refactor get extensions details workflow

extensions/quarto-extensions.csv
=> chore: add EmilHvitfeldt/quarto-revealjs-imagemover

extensions/quarto-extensions.csv
I confirm that I have checked that:
- There are no special characters/strings in the **Description**, such as `'<style>'` instead of `` `<style>` ``.
Style computational output, errors, warnings, and messages in HTML documents
=> chore: add quarto-output-styling extension

assets/scripts/quarto-extensions-listing.html
Enhance the search functionality to include user and organisation names, 
Fixes #202.
=> feat: Extend search to include user/organisation names
